### ISSUE TITLE
Reading -psf as a directory and not a size

### ISSUE THREAD

**Issue by Kincaidr** [Athanaseus/aimfast#51]
**When running the command to get residual comparison of two images:**

```
aimfast --residual-image image_DI_Clustered.DeeperDeconv.app.residual.fits --tigger-model image_DI_Clustered.DeeperDeconv.app.restored-pybdsf.lsm.html --normality-test normaltest -psf 7.5 -af 5 --html-prefix kms --outfile cluster_fidelity_results.json

```

**I get this error:**

```
aimfast.aimfast - 2021-08-04 20:43:26,050 INFO - Welcome to AIMfast
aimfast.aimfast - 2021-08-04 20:43:26,050 INFO - Version: 1.0.0
Traceback (most recent call last):
  File "/home/kincaid/venv/bin/aimfast", line 5, in <module>
    main()
  File "/home/kincaid/venv/lib/python3.6/site-packages/aimfast/aimfast.py", line 2475, in main
    psf_size = measure_psf(args.psf)
  File "/home/kincaid/venv/lib/python3.6/site-packages/aimfast/aimfast.py", line 217, in measure_psf
    with fitsio.open(psffile) as hdu:
  File "/home/kincaid/venv/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 164, in fitsopen
    lazy_load_hdus, **kwargs)
  File "/home/kincaid/venv/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 402, in fromfile
    lazy_load_hdus=lazy_load_hdus, **kwargs)
  File "/home/kincaid/venv/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 1051, in _readfrom
    fileobj = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
  File "/home/kincaid/venv/lib/python3.6/site-packages/astropy/utils/decorators.py", line 535, in wrapper
    return function(*args, **kwargs)
  File "/home/kincaid/venv/lib/python3.6/site-packages/astropy/io/fits/file.py", line 175, in __init__
    self._open_filename(fileobj, mode, overwrite)
  File "/home/kincaid/venv/lib/python3.6/site-packages/astropy/io/fits/file.py", line 564, in _open_filename
    self._file = fileobj_open(self.name, IO_FITS_MODES[mode])
  File "/home/kincaid/venv/lib/python3.6/site-packages/astropy/io/fits/util.py", line 397, in fileobj_open
    return open(filename,  -psf PSF, --psf-image PSF
                        Name of the point spread function file or psf size in
                        arcsec
mode, buffering=0)
FileNotFoundError: [Errno 2] No such file or directory: '7.5'
````
From the help file, it either looks for a file or a beam size. But it seems its only performing the looking for file option:

![image](https://user-images.githubusercontent.com/53697426/128237361-ac45bbc3-9dd8-45cc-bbe1-a4b292654e1b.png)

**Comment by Athanaseus** [comment]
Hey @Kincaidr 

This was fixed in the master branch.

Please install the master by:

`pip install git+https://github.com/Athanaseus/aimfast.git`

**Comment by Kincaidr** [comment]
Ok thanks working now
