### ISSUE TITLE
aimfast applied to self-calibrated images

### ISSUE THREAD

**Issue by Athanaseus** [Athanaseus/aimfast#7]
-------------------------------------
Self calibration in a nutshell
![self_cal](https://user-images.githubusercontent.com/16665629/35670926-8f5e8630-0742-11e8-93ac-d8aa387dab51.png)
--------------------------------------
* This issue involves creating a meerkathi worker that performs self-calibration.
* Subsequent to every imaging step, aimfast will be used assess the image quality.
* Stopping criteria
   - Set the number of iterations to perform self-cal : No need to iterate infinitely
   - Set tolerance [for DR, 4-moments] : No need to iterate further if image quality doesn't improve
   - Set expected 4-moments of residual flux distribution [Say Gaussian] : No need to iterate further if statistical conditions are satisfied.

**Comment by Athanaseus** [comment]
@SpheMakh I see in the installation of meerkathi, we only need to build stimela, does it pull images automatically when installing or? 
- Also can I pull a specific stimela image like stimela/aimfast? (Looks like it's no found in the current stimela release)

**Comment by Athanaseus** [comment]
Thanks @SpheMakh 
Do I have to do anything special to pull `stimela/aimfast` cab? meerkathi does not find it?

**Comment by Athanaseus** [comment]
`$ stimela cabs -i aimfast`

```Traceback (most recent call last):
  File "/data/ramaila/meerkathi-workdir/meerkathi-venv/bin/stimela", line 13, in <module>
    stimela.main([a for a in sys.argv[1:]])
  File "/data/ramaila/meerkathi-workdir/meerkathi-venv/local/lib/python2.7/site-packages/stimela/__init__.py", line 608, in main
    _cmd(argv)
  File "/data/ramaila/meerkathi-workdir/meerkathi-venv/local/lib/python2.7/site-packages/stimela/__init__.py", line 226, in cabs
    raise RuntimeError('The cab you requested is not known to stimela, or has not been built. Run \'stimela cabs -l\' to see which cabs have been built')
RuntimeError: The cab you requested is not known to stimela, or has not been built. Run 'stimela cabs -l' to see which cabs have been built```

**Comment by SpheMakh** [comment]
did you build the cab?

**Comment by Athanaseus** [comment]
Build a specified cab:
`stimela build -c aimfast,<path to Docker file>`

**Comment by Athanaseus** [comment]
@SpheMakh I'm revamping [aimfast](https://github.com/Athanaseus/aimfast).
**Currently**:
- If user provide restored image, output is DR (determined by brightest source/deepest negative around source position) only. 
- If user provide residual image, output is the 4-moments only.
If user provides both, gets both outputs

**Plan** (Due to the case of meerkathi):
- Current will still apply.
- User can provide model lsm.html and residual image (mandatory) to get both outputs.
   - DR (determined by brightest source in model/deepest negative around source position in residual).

**Question**
Are model sources flux unit compatible with residual flux?

**Comment by SpheMakh** [comment]
Technically no, sky model flux is Jy and residual image flux is Jy/beam. But the DR values will be consistently off by a factor of "beam", so it doesn't bias anything

**Comment by Athanaseus** [comment]
self cal loop that terminates on the number of loops specified
---------------------------------------------------------------------------------

**Config**
========
```self_cal1:

  __helpstr: Self calibration
  enable: yes
  label: corr
  order: 10
  primary_beam: no
  calibrate_with: meqtrees
  spwid: 0
  # Imaging settings
  img_npix: 8192                            # at very least 50% padding for alias protection
  img_trim: 5540
  img_mgain: 0.9
  img_cell: 1.3
  img_weight: briggs
  img_robust: -1.5
  img_niter: 1000000
  img_auto_threshold: 3                     # Cleaning threshold for cleaning
  img_auto_mask: 5                          # Masking threshold (will be recalculated every clean major loop)
  img_cleanborder: 0
  img_facets: 11                            # No implemented 
  img_nchans: 3                             # Number of output channels for imaging
  img_joinchannels: yes
  img_fit_spectral_pol: 1                   # Fit a polynomial over frequency to each clean component
  img_column: CORRECTED_DATA                # Column to image
  img_pol: I
  # Calibration settings
  cal_niter: 4                              # Number self cal iterations
  cal_Gsols: auto                           # calibration solution intervals: [time_bins, freq_bins], zero means full interval. 'auto' means that these will calculated internally
  cal_DDsols: [300, 500]                    # direction dependent gain solution intervals (not implemented)
  cal_gain_amplitude_clip_low: 0.5          # Flag data if corresponding gain has a value below this
  cal_gain_amplitude_clip_high: 1.5         # Flag data if corresponding gain has a value above this
  # Source finding settings
  sf_thresh_pix: 10                         # Peak threshold for source finder (in sigma above noise)
  sf_thresh_isl: 8                          # Island threshold for source finder (in sigma above noise)
  image:                                    # Make intial image 
    enable: yes
    auto_mask: 40
    auto_threshold: 0.5
    column: DATA
  extract_sources:                          # Find sources in image
    enable: yes
    spi: yes                                # Add spectral indices to skymodel (img_chans must be >1 in this for this to work)
  calibrate:
    enable: yes
    output_data: CORR_DATA                  # Data to output after calibration. Options are CORR_RES (corrected residual), CORR_DATA (corrected data), RES (residual data)
    gain_matrix_type_1: GainDiagPhase       # Gain matrix type. Options are GainDiagPhase, GainDiag, Gain2x2
    gain_matrix_type_n: GainDiag            # The rest of calibration loops gain matrix 
  aimfast:                                  # aimfast settings
    DR_tolerance: 0.1                       # Convergence factor of dynamic range. i.e. 0 = 0% relative change from latter to current iter
    area_factor: 10                         # Peak flux source area multiplying factor i.e tot_area = psf-size*af
  restore_model:                            # Restore modelled to final calibrated residual image
    enable: yes
    model: '2+3'
    clean_model: '4'
  flagging_summary:
    enable: yes
```


**Worker**
========

**aimfast cab**
```
def image_quality_assessment(num):
    step = 'aimfast'
    recipe.add('cab/aimfast', step,
          {
                 "tigger-model"         : '{0:s}_{1}-pybdsm.lsm.html'.format(prefix, num),
                 "residual-image"       : '{0:s}_{1}-cube.fits'.format(prefix, num+1),
                 "area-factor"          : config.get('area_factor', 10)
          },
                 input=pipeline.output,
                 output=pipeline.output,
                 label="{0:s}:: Image fidelity assessment for {1}".format(step, num))
```

**cal models**
```
if num <= 2:
    model = '%s' % num
else:
    counter = 1
    model = ''
    while counter < num:
        model += '%s+' % counter
        counter += 1
        if counter == num:
            model = model[:-1]
```

**quality check**
```
def quality_check(num):
    "Examine the aimfast results to see if they meet specified conditions"
    tolerance = config.get('DR_tolerance', 1)
    # If total number of iterations is reached stop
    if num > cal_niter:
        return True
    # Ensure atleast one iteration is ran to compare previous and subsequent images
    if num > 2:
        data = get_aimfast_data()
        DR0 = data['/{0:s}/{1:s}_{2}-pybdsm.lsm.html'.format(pipeline.input, prefix, num - 1)]['DR']
        DR1 = data['/{0:s}/{1:s}_{2}-pybdsm.lsm.html'.format(pipeline.input, prefix, num)]['DR']
        # Cornfirm that previous mage DR is smaller than subsequent image
        # Also make sure the difference is greater than the tolerance
        if DR1 - DR0 < tolerance:
            return True
    # If no condition is met return false to continue
    return False
```

**selfcal loop**
```
iter_counter = 1
image(iter_counter)
while not quality_check(iter_counter):
    extract_sources(iter_counter)
    calibrate(iter_counter)
    iter_counter += 1
    image_quality_assessment(iter_counter)
```

**Comment by Athanaseus** [comment]
This was implemented in MeerKATHI (https://github.com/ska-sa/meerkathi)
